### ISSUE TITLE
sbt analogue for `mvn sonar:sonar -Dsonar.host.url=http://localhost:9000`

### ISSUE THREAD

**Issue by sslavian812** [mwz/sbt-sonar#28] opened 2019-03-03 18:27 UTC
I have your docker-container with sonarqube (https://github.com/mwz/sonar-scala-docker) running.
I'd like to analyse my `sbt` project with it, but I'm struggling with this part.
For a maven mroject I can simply use this: `mvn sonar:sonar -Dsonar.host.url=http://localhost:9000`

Is there analogue for sbt?
I added `addSbtPlugin("com.github.mwz" % "sbt-sonar" % "1.6.0")` to my plugins, but the line
```
sbt -Dsonar.projectName=dev-projectName sonarScan
```
does not work for me and complains about `SONAR_SCANNER_HOME`. Seems `sonar-scanner` indeed has to be installed at my machine. Can I avoid that?

The ideal case would be cloning repository and running an sbt command to analyse it with remote sonar instance. Is it possible to do that?

**Comment by mwz** [comment] 2019-03-03 18:41
> Seems `sonar-scanner` indeed has to be installed at my machine. Can I avoid that?

Yes, currently sbt-sonar requires sonar-scanner cli to be installed on your machine, however, there is some work in progress to use the embedded scanner api instead so it won't be necessary to have sonar-scanner cli installed once (#20) is completed. I'm planning to pick it up and finish it off soon, so stay tuned for updates.

**Comment by mwz** [comment] 2019-03-11 21:10
Duplicate of #19.

**Closed by mwz** 2019-03-11 21:10 UTC

**Comment by robbyki** [comment] 2019-05-22 19:00
any update on this? would be a great feature.

**Comment by mwz** [comment] 2019-05-22 20:27
It's next on my list after https://github.com/mwz/sonar-scala/pull/196 is done.

**Comment by robbyki** [comment] 2019-05-23 13:39
Thank you. In the mean time, I'm trying to just package the cli along with my sbt build. What's the proper way to set `sys.props.get("sonarScanner.home")` inside `build.sbt` so that I can run `sonarScan`?

**Comment by mwz** [comment] 2019-05-23 17:39
> I'm trying to just package the cli along with my sbt build.

I'm not sure what you mean by that, can you elaborate, please?

> What's the proper way to set `sys.props.get("sonarScanner.home")` inside `build.sbt` so that I can run `sonarScan`

You can either export the `SONAR_SCANNER_HOME` environment variable or you can set the `sonarScanner.home` property explicitly when running sbt, e.g. `sbt -DsonarScanner.home=~/bin/sonar-scanner sonarScan`.

**Comment by mwz** [comment] 2019-06-16 23:08
Hi @sslavian812, @robbyki - I released version 2.0 of sbt-sonar, which no longer requires the sonar-scanner cli.
